---
# tasks file for jenkins configure

- name: Download jenkins-cli
  get_url:
    url: "{{ jenkins_cli_uri }}"
    dest: "{{ jenkins_cli }}"
    force: yes

- name: Log into jenkins-cli with entered password
  ignore_errors: yes
  command: "{{ jenkins_cli_cmd }} login --username {{ jenkins_admin.user }} --password {{ jenkins_admin.password }}"
  register: login_result

- name: Get first-time password if login failed
  command: "head -1 {{ jenkins_initial_passwd }}"
  register: initial_passwd
  when: login_result.rc != 0

- name: Extract temporary password
  set_fact:
    jenkins_admin:
      user: "{{ jenkins_admin.user }}"
      password: "{{ initial_passwd.stdout }}"
  when: login_result.rc != 0

- name: Log into jenkins-cli with temporary password
  command: "{{ jenkins_cli_cmd }} login --username {{ jenkins_admin.user }} --password {{ jenkins_admin.password }}"
  when: login_result.rc != 0
