---
# tasks file for jenkins

##########################
# INSTALL/UPDATE JENKINS #
##########################

- name: Install jenkins
  include: install_jenkins.yml
  when: inventory_hostname in groups['jenkins-master']
  tags:
    - install

###############################
# VALIDATE AUTH CONFIGURATION #
###############################

- name: Validate authentication
  include: first_auth.yml
  static: no
  when: inventory_hostname in groups['jenkins-master']

############################
# CONFIGURE ADMIN SETTINGS #
############################

- name: Configure admin settings
  include: configure_admin.yml
  static: no
  when: inventory_hostname in groups['jenkins-master']  

#################################
# INSTALL LIST OF GIVEN PLUGINS #
#################################

- name: Install plugins
  include: install_plugins.yml
  static: no
  when: inventory_hostname in groups['jenkins-master']
  tags:
    - plugins

##############################################################################
# CONFIGURE SLAVES TO BE ADDED TO THE JENKINS MASTER (SSH-SLAVES PLUGIN REQ) #
##############################################################################

- name: Configure slaves
  include: configure_slaves.yml jenkins_slave="{{ item }}"
  static: no
  with_items: "{{ groups['jenkins-slave'] }}"
  when: inventory_hostname in groups['jenkins-master']
  tags:
    - slaves

######################################################################
# CONFIGURE GITHUB AUTHENTICATION (REQUIRES CONFIGURATION ON GITHUB) #
######################################################################

- name: Configure authentication
  include: github_auth.yml
  static: no
  when: inventory_hostname in groups['jenkins-master']
  tags:
    - auth

- name: Jenkins Url
  debug: msg={{ jenkins_uri }}
  when: inventory_hostname in groups['jenkins-master']
